apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: ingress-tls
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-__CERT_API_ENVIRONMENT__
spec:
  tls:
  - hosts:
    - __DNS_DOMAIN_NAME__
    secretName: tls-secret
  rules:
  - host: __DNS_DOMAIN_NAME__
    http:
      paths:
      - backend:
          serviceName: azure-vote-front
          servicePort: 80
        path: /(.*)
      - backend:
          serviceName: nexus
          servicePort: 8081
        path: /nexus(/|$)(.*)
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-static
  namespace: ingress-tls
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /static/$2
    cert-manager.io/cluster-issuer: letsencrypt-__CERT_API_ENVIRONMENT__
spec:
  tls:
  - hosts:
    - __DNS_DOMAIN_NAME__
    secretName: tls-secret
  rules:
  - host: __DNS_DOMAIN_NAME__
    http:
      paths:
      - backend:
          serviceName: azure-vote-front
          servicePort: 80
        path: /static(/|$)(.*)
